import pandas as pd

sampleDF = pd.read_table(config["INPUT_DF"])

sampleDF["Raw"] = sampleDF["Source"] + "." + sampleDF["Rep"]
sampleDF["RawSample"] = sampleDF["Path"].str.rsplit("/", 1, expand=True)[1]

ref = config["REF"]["NAME"]
bwNorm = config["OUTPUT"]["BW_NORMALIZATIONS"]

outputs = []

if config["OUTPUT"]["RUN"]["QC"]:
    outputs += ["qc/multiqc_report.html"]

if config["OUTPUT"]["RUN"]["PEAKS"]:
    outputs += [
        f"results_{ref}/peaks/{raw}_peaks.narrowPeak"
        for raw in sampleDF["Raw"]
        if raw.find("input") == -1
    ]

if config["OUTPUT"]["RUN"]["BWS"]:
    outputs += [
        f"results_{ref}/bigwig/{raw}.genomecov.{norm}.bw"
        for raw in sampleDF["Raw"]
        for norm in bwNorm
    ]

if config["OUTPUT"]["RUN"]["CHIPATLAS_BEDS"]:
    threshold = config["OUTPUT"]["CHIPATLAS_THRESHOLD"]
    outputs += [
        f"results_{ref}/cabeds/{srx}.{threshold}.bed"
        for raw in sampleDF["RawSample"]
    ]

if config["OUTPUT"]["RUN"]["CHIPATLAS_BWS"]:
    outputs += [
        f"results_{ref}/cabigwig/{srx}.bw"
        for raw in sampleDF["RawSample"]
    ]

rule all:
    input:
        expand("{out_}", out_=outputs)

include: "rules/qc.smk"
include: "rules/sra.smk"
include: "rules/premap.smk"
include: "rules/map.smk"
include: "rules/peaks.smk"
include: "rules/bw.smk"

include: "rules/chipatlas.smk"

# TODO: Rule name standard
# TODO: Tidiness

