



configfile: "config/config.yaml"
# Cluster config

import pandas as pd

PATH_ = "/groups/lackgrp/ll_members/berkay/1-notebook/s-HOXB13/public/atacseq"


sampleDF = pd.read_table(config["INPUT"]["DF"])

input_column=config["INPUT"]["NAMES"]

outputs = []

if config["OUTPUT"]["RUN"]["QC"]:
    outputs += "qc/multiqc_report.html"

if config["OUTPUT"]["RUN"]["PEAKS"]:

    outputs += [
        f"results_{ref}/bw/{raw}.{type_}.bw"
        for raw in sampleDF[input_column]
        for ref in config["OUTPUT"]["REF"]
        for type_ in config["OUTPUT"]["MACS3_TYPE"]
    ]



rule all:
    input:
        expand("{out_}", out_=outputs)


include: "rules/qc.smk"
include: "rules/sra.smk"
include: "rules/premap.smk"
include: "rules/map.smk"

