

import pandas as pd

sampleDF = pd.read_table(config["INPUT_DF"])

sampleDF["Raw"] = sampleDF["Source"] +"."+ sampleDF["Rep"]
sampleDF["RawSample"] = sampleDF["Path"].str.rsplit("/", 1, expand=True)[1]

ref = config["REF"]["NAME"]

outputs = []

if config["OUTPUT"]["RUN"]["QC"]:
    outputs += ["qc/multiqc_report.html"]

if config["OUTPUT"]["RUN"]["PEAKS"]:
    outputs += [
        f"results_{ref}/bw/{raw}.{type_}.bw"
        for raw in sampleDF["Raw"]
        for type_ in config["OUTPUT"]["MACS3_TYPE"]
    ]

rule all:
    input:
        expand("{out_}", out_=outputs)


include: "rules/qc.smk"
include: "rules/sra.smk"
include: "rules/premap.smk"
include: "rules/map.smk"
include: "rules/peaks.smk"

